### ISSUE TITLE
两条开发建议

### ISSUE THREAD

**Issue by ilgnefz** [lyming99/wenznote#2]
1. 因为框架本身的关系，中文显示不是很友好。有两个解决方案，一是开发时使用自定义字体，二是使用 [chinese_font_libary](https://pub.dev/packages/chinese_font_library) 这个包。
2. 因为隐藏了系统默认的 titlebar，在 windows 系统上显示有一个  bug。可以参考 [window_manager#417](https://github.com/leanflutter/window_manager/issues/417) 这个问题下我的方案。在 win11 上软件的风格都是圆角，这个需要软件自己适配，你有需要的话可以用 Container 包括 MaterialApp 这个组件设置圆角和阴影。

**Comment by lyming99** [comment]
非常感谢，这2个建议都很有用

**Comment by lyming99** [comment]
已经在windows10和windows7使用了自定义边框，字体也采用了chinese_font_libary，感觉都是治标不治本，字体还是没有办法和chrome相比，边框也不够完美，先关闭了这个，后面考虑采用gdi绘制文字了
