### ISSUE TITLE
添加中文字符“、”触发格式选择框

### ISSUE THREAD

**Issue by N07Cc** [lyming99/wenznote#6]
英文字符"/"正常触发：
![image](https://github.com/lyming99/wenznote/assets/80192941/48e8c1fd-e506-4ed8-8ff8-633f4602f495)
中文字符“、”无法触发：
![image](https://github.com/lyming99/wenznote/assets/80192941/b24d547c-0fc2-48a2-8b32-e8353ed75ccb)
希望能够添加这一功能

**Comment by lyming99** [comment]
中文输入模式下，也可以输入"/"呀，为啥要增加"、"支持呢

**Comment by N07Cc** [comment]
> 中文输入模式下，也可以输入"/"呀，为啥要增加"、"支持呢

但是中文输入模式下，如果不是打开了半角标点，想要输入"/"就需要多按两次Shift，会有一种输入被打断的感觉

**Comment by lyming99** [comment]
> > 中文输入模式下，也可以输入"/"呀，为啥要增加"、"支持呢
> 
> 但是中文输入模式下，如果不是打开了半角标点，想要输入"/"就需要多按两次Shift，会有一种输入被打断的感觉

可能是输入法的问题，行，可以增加这个支持

**Comment by N07Cc** [comment]
(๑•̀ㅂ•́)و✧

**Comment by FlysoftBeta** [comment]
@lyming99  这个换成组合键感觉会好一点？

**Comment by lyming99** [comment]
> @lyming99  这个换成组合键感觉会好一点？

没有那么方便啊😫

**Comment by lyming99** [comment]
> @lyming99  这个换成组合键感觉会好一点？

不过想了下，确实也可以
